"""empty message

Revision ID: 219f8542e7dc
Revises: 
Create Date: 2022-02-16 14:49:28.387220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '219f8542e7dc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menus',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=20), nullable=False),
    sa.Column('icon', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('menu_child',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sec_title', sa.String(length=20), nullable=False),
    sa.Column('icon', sa.String(length=128), nullable=True),
    sa.Column('menu_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['menu_id'], ['menus.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sec_title')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('menu_child')
    op.drop_table('menus')
    # ### end Alembic commands ###
